### PR TITLE
Modified Random Forest Classifier.

### PR DESCRIPTION
**Pull request by findkim**

### CODE REVIEW

**Comment by alexmwu** [comment]
you could also add a gitignore and add *.pyc to it

**Comment by alexmwu** [comment]
not to be nitpicky but you used a 3:1 training to testing ratio. just need to make sure we get that right for the report

**Comment by alexmwu** [comment]
I don't think you did full cross validation. you just split the data into testing and training and predicted on training. I don't believe you ran scoring on the validation sets for each iteration (correct me if I'm wrong). Here is the link that you probably used: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators. Read the section on cross_val_score

**Comment by alexmwu** [comment]
Finally, how did you generate those graphs?

**Comment by alexmwu** [comment]
oh using output csvs and excel or something?

**Comment by findkim** [comment]
Yeah you're right, I didn't do a full cross-validation. I'll modify it.

I used matplotlib.pyplot to plot the graphs.

**Comment by findkim** [comment]
My bad about the 4:1. I'll be sure to write 3:1 in the report.

**Comment by findkim** [comment]
i updated the results after adding 5-fold cross validation.

**Pull request merged**
